apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app: jenkins # ต้องตรงกับ label ใน Deployment
  ports:
    - protocol: TCP
      port: 8080         # Port ของ Service
      targetPort: 8080   # Port ของ Pod ที่ต้องการส่งไปหา
  type: LoadBalancer