upstream app1 {
        server 127.0.0.1:8000;
        server 127.0.0.1:8001;
    }
upstream app2 {
        server 127.0.0.1:8080;
        server 127.0.0.1:8081;
    }

server {
        listen 80;
        #server_name example.com;

        # ส่วนการตรวจสอบสิทธิ์ (Authentication Logic)
        location /v1/ {
            # ตรวจสอบว่ามี Header ชื่อ X-API-KEY และค่าตรงกับที่กำหนดไว้หรือไม่
            # ในที่นี้สมมติ Key คือ "my-super-secret-123"
            if ($http_x_api_key != "abc1234") {
                # ถ้า Key ไม่ถูกต้อง หรือไม่มีมา ให้ส่ง 403 Forbidden กลับไป
                return 403 '{"error": "Invalid or Missing API Key"}';
                add_header Content-Type application/json;
            }

            # ถ้า Key ถูกต้อง ให้ส่งคำขอต่อไปยัง Backend
            proxy_pass http://app1/api;
    
            # ส่งข้อมูล Client จริงๆ ไปให้ Backend ด้วย (เพื่อเก็บ Log)
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /v2/ {
            # ตรวจสอบว่ามี Header ชื่อ X-API-KEY และค่าตรงกับที่กำหนดไว้หรือไม่
            if ($http_x_api_key != "xyz5678") {
                # ถ้า Key ไม่ถูกต้อง หรือไม่มีมา ให้ส่ง 403 Forbidden กลับไป
                return 403 '{"error": "Invalid or Missing API Key"}';
                add_header Content-Type application/json;
            }

            # ถ้า Key ถูกต้อง ให้ส่งคำขอต่อไปยัง Backend
            proxy_pass http://app2/user;

            # ส่งข้อมูล Client จริงๆ ไปให้ Backend ด้วย (เพื่อเก็บ Log)
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
}
